baseURL: http://wedding.tan-li.info
languageCode: en-us
title: Kelly Tan & Eric Li

params:
  ga: ''

disableKinds:
  - "taxonomy"
  - "term"
  - "RSS"
markup:
  goldmark:
    renderer:
      unsafe: true